version: '3.9'

services:
  app:
    image: node:18-alpine3.17
    container_name: 'waiterappV2'
    ports:
      - '5173:5173'
    command: npm run dev
    working_dir: /app
    volumes:
      - .:/app

